"""Script to run the clustering algorithm for compositional explanations.
"""

import os

import torch
import absl.flags
import absl.app
import numpy as np



from compositional import mask_utils
from compositional import utils
from compositional import formula as F
from src import utils
from src import settings
from utils import common_flags # import all user flags
from utils import segmentor_utils

# Flags specific to this script
absl.flags.DEFINE_string("output_path", "output/explanations", "output path")

FLAGS = absl.flags.FLAGS

def main(argv):
    if FLAGS.num_clusters < 1:
        raise ValueError("num_clusters must be greater than 0")
    # Set seed
    utils.set_seed(FLAGS.seed)

     # Parameters
    cfg = settings.Settings(
        model= FLAGS.model, 
        pretrained= FLAGS.pretrained, 
        dataset=FLAGS.dataset,
        num_clusters=FLAGS.num_clusters,
        beam_limit=FLAGS.beam_limit,
        heuristic=FLAGS.heuristic,
        length=FLAGS.length,
        layer=FLAGS.layer,
        device=FLAGS.device,
        root_models=FLAGS.root_models,
        root_datasets=FLAGS.root_datasets,
        root_segmentations=FLAGS.root_segmentations,
        root_activations=FLAGS.root_activations,
        root_results=FLAGS.root_results,
        configuration_name=FLAGS.name_configuration,
        granularity=FLAGS.granularity,
        additional_concepts=FLAGS.add_concepts,
        experiment_name=FLAGS.name_experiment,
        additional_dataset=FLAGS.additional_dataset,
        unification_files=FLAGS.unification_files,
    )
    mask_shape = cfg.get_mask_shape()
    configuration_name = cfg.configuration_name 
    experiment_config = cfg.get_experiment_config()
    
    # Load Activations
    layer_activations = utils.get_layer_activations(cfg)
    
    # Select Units
    selected_units = utils.get_selected_units(layer_activations, units=FLAGS.units, random_units=FLAGS.random_units)
    selected_units = selected_units[FLAGS.starting_unit:FLAGS.ending_unit]
    for segmentor_name in list(FLAGS.segmentors):
        # Set seed
        generator = utils.set_seed(FLAGS.seed)
        
        segmentor_experiment_config = experiment_config.copy()
        # Load Masks, Segmentor Labels and Experiment Name
        print("Loading Masks generated by ", segmentor_name)
        concepts = cfg.get_concepts(FLAGS.concepts_type, FLAGS.additional_dataset)
        experiment_name = segmentor_utils.get_experiment_name(segmentor_name, segmentor_experiment_config, concepts)
        segmentor_labels = segmentor_utils.get_segmentor_concepts(segmentor_name, segmentor_experiment_config, concepts, [])

        # Compute Compositional Explanations
        segmentor_experiment_config['segmentor_name'] = segmentor_name
        segmentor_experiment_config['segmentor_labels'] = segmentor_labels

        def get_explanations(heuristic):
            results_dir = utils.get_result_dir(
                cfg.get_root_results(), heuristic, configuration_name, cfg.dataset, segmentor_name, mask_shape, experiment_name, cfg.model, cfg.granularity, cfg.additional_dataset)    
            h_config = segmentor_experiment_config.copy()
            h_config['results_dir'] = results_dir
            h_compo_config = cfg.get_explanation_config() 
            h_compo_config['heuristic'] = heuristic
            h_exp = utils.load_compositional_explanations(
                None, None, None, layer_activations, selected_units, 
                h_config, h_compo_config, verbose=False)
            return h_exp


        mmesh_compo_exp = get_explanations('mmesh')
        mmesh_total_visited = []
        mmesh_total_expanded = []
        mmesh_total_estimated = []
        mmesh_total_time = []
        mmesh_ious = []

        optimal_compo_exp = get_explanations('optimal')
        optimal_total_visited = []
        optimal_total_expanded = []
        optimal_total_estimated = []
        optimal_total_time = []
        optimal_ious = []

        beam_optimal_compo_exp = get_explanations('beam_optimal')
        beam_optimal_total_visited = []
        beam_optimal_total_expanded = []
        beam_optimal_total_estimated = []
        beam_optimal_total_time = []

        vanilla_compo_exp = get_explanations('none')
        vanilla_total_visited = []
        vanilla_total_expanded = []
        vanilla_total_estimated = []
        vanilla_total_time = []

        num_diff = 0
        total_meaningful = 0
        less_then_mmesh = 0
        same_concepts_diff_iou = 0
        same_concepts_equal_iou = 0
        bugged = []

        for index in range(len(selected_units)):
            (unit, cluster_index, _, mmesh_label, mmesh_string_label, mmesh_best_iou, mmesh_visited, mmesh_expanded, mmesh_estimated, mmesh_time_taken) = mmesh_compo_exp[index]
            if mmesh_label is not None:
                mmesh_total_visited.append(mmesh_visited)
                mmesh_total_expanded.append(mmesh_expanded)
                if mmesh_estimated > -1:
                    mmesh_total_estimated.append(mmesh_estimated)
                if mmesh_time_taken > -1:
                    mmesh_total_time.append(mmesh_time_taken)
            (_, _, _, optimal_label, optimal_string_label, optimal_iou, optimal_visited, optimal_expanded, optimal_estimated, optimal_time_taken) = optimal_compo_exp[index]
            if optimal_label is not None:
                optimal_total_visited.append(optimal_visited)
                optimal_total_expanded.append(optimal_expanded)
                if optimal_estimated > -1:
                    optimal_total_estimated.append(optimal_estimated)
                if optimal_time_taken > -1:
                    optimal_total_time.append(optimal_time_taken)
            (_, _, _, beam_optimal_label, beam_optimal_string_label, beam_optimal_iou, beam_optimal_visited, beam_optimal_expanded, beam_optimal_estimated, beam_optimal_time_taken) = beam_optimal_compo_exp[index]
            if beam_optimal_label is not None:
                beam_optimal_total_visited.append(beam_optimal_visited)
                beam_optimal_total_expanded.append(beam_optimal_expanded)
                if beam_optimal_estimated > -1:
                    beam_optimal_total_estimated.append(beam_optimal_estimated)
                if beam_optimal_time_taken > -1:
                    beam_optimal_total_time.append(beam_optimal_time_taken)
            (_, _, _, vanilla_label, vanilla_string_label, vanilla_iou, vanilla_visited, vanilla_expanded, vanilla_estimated, vanilla_time_taken) = vanilla_compo_exp[index]
            if vanilla_label is not None:
                vanilla_total_visited.append(vanilla_visited)
                vanilla_total_expanded.append(vanilla_expanded)
                if vanilla_estimated > -1:
                    vanilla_total_estimated.append(vanilla_estimated)
                if vanilla_time_taken > -1:
                    vanilla_total_time.append(vanilla_time_taken)
            if mmesh_label is not None and optimal_label is not None:
                total_meaningful += 1
                if mmesh_label != optimal_label:
                    if optimal_iou < mmesh_best_iou:
                        less_then_mmesh += 1
                        print(f"BUGGED: Optimal < M-MESH for Unit {unit} Cluster {cluster_index} - M-MESH: {mmesh_string_label} {mmesh_label} ({mmesh_best_iou:}) - Optimal: {optimal_string_label} {optimal_label} ({optimal_iou:})")
                        bugged.append(unit)
                    else:
                      
                        atoms_mmesh = mmesh_label.get_vals()
                        atoms_optimal = optimal_label.get_vals()
                        if set(atoms_mmesh) == set(atoms_optimal):
                            if optimal_iou != mmesh_best_iou:
                                same_concepts_diff_iou += 1
                            else:
                                same_concepts_equal_iou += 1
                            print(f"Same Concepts different formula for Unit {unit} Cluster {cluster_index} - M-MESH: {mmesh_string_label} {mmesh_label} ({mmesh_best_iou}) - Optimal: {optimal_string_label} {optimal_label} ({optimal_iou})")
            
                        mmesh_ious.append(mmesh_best_iou)
                        optimal_ious.append(optimal_iou)
                        print(f"Unit {unit}")
                        print(f"M-MESH: {mmesh_string_label} ({mmesh_best_iou:<.3f})")
                        print(f"Optimal: {optimal_string_label} ({optimal_iou:<.3f})")
                        print()

                    num_diff += 1
                    #print(f"Different Results for Unit {unit} Cluster {cluster_index} - M-MESH: {mmesh_string_label} {mmesh_label} ({mmesh_best_iou}, visited {mmesh_visited}) - Optimal: {optimal_string_label} {optimal_label} ({optimal_iou}, visited {optimal_visited})")
        print(f"Number of different results: {num_diff} out of {total_meaningful} units")
        print(f"Number of times Optimal < M-MESH: {less_then_mmesh} list of units: {bugged}")
        if len(mmesh_ious) > 0 and len(optimal_ious) > 0:
            print(f"Average M-MESH IoU over {len(mmesh_ious)}: {np.mean(mmesh_ious):.4f} - Standard Deviation: {np.std(mmesh_ious):.4f}")
            print(f"Average Optimal IoU over {len(optimal_ious)}: {np.mean(optimal_ious):.4f} - Standard Deviation: {np.std(optimal_ious):.4f}")
            print(f"Number of times A different formula and iou: {(len(optimal_ious)- same_concepts_diff_iou - same_concepts_equal_iou)/len(optimal_ious)}")
            print(f"Number of times B same concepts different iou and formula: {same_concepts_diff_iou/len(optimal_ious)}")
            print(f"Number of times C same concepts same iou and different formula: {same_concepts_equal_iou/len(optimal_ious)}")
        print(f"Total Units: {len(selected_units)}")
        print(f"Optimal Average Visited over {len(optimal_total_visited)}: {np.mean(optimal_total_visited):.2f} - Standard Deviation: {np.std(optimal_total_visited):.2f}")
        print(f"Optimal Average Expanded over {len(optimal_total_expanded)}: {np.mean(optimal_total_expanded):.2f} - Standard Deviation: {np.std(optimal_total_expanded):.2f}")
        print(f"Optimal Average Estimated over {len(optimal_total_estimated)}: {np.mean(optimal_total_estimated):.2f} - Standard Deviation: {np.std(optimal_total_estimated):.2f}")
        print(f"Optimal Average Time over {len(optimal_total_time)}: {np.mean(optimal_total_time):.2f} seconds - Standard Deviation: {np.std(optimal_total_time):.2f} seconds")
        print(f"Beam Optimal Average Visited over {len(beam_optimal_total_visited)}: {np.mean(beam_optimal_total_visited):.2f} - Standard Deviation: {np.std(beam_optimal_total_visited):.2f}")
        print(f"Beam Optimal Average Expanded over {len(beam_optimal_total_expanded)}: {np.mean(beam_optimal_total_expanded):.2f} - Standard Deviation: {np.std(beam_optimal_total_expanded):.2f}")
        print(f"Beam Optimal Average Estimated over {len(beam_optimal_total_estimated)}: {np.mean(beam_optimal_total_estimated):.2f} - Standard Deviation: {np.std(beam_optimal_total_estimated):.2f}")
        print(f"Beam Optimal Average Time over {len(beam_optimal_total_time)}: {np.mean(beam_optimal_total_time):.2f} seconds - Standard Deviation: {np.std(beam_optimal_total_time):.2f} seconds")
        print(f"M-MESH Average Visited over {len(mmesh_total_visited)}: {np.mean(mmesh_total_visited):.2f} - Standard Deviation: {np.std(mmesh_total_visited):.2f}")
        print(f"M-MESH Average Expanded over {len(mmesh_total_expanded)}: {np.mean(mmesh_total_expanded):.2f} - Standard Deviation: {np.std(mmesh_total_expanded):.2f}")
        print(f"M-MESH Average Estimated over {len(mmesh_total_estimated)}: {np.mean(mmesh_total_estimated):.2f} - Standard Deviation: {np.std(mmesh_total_estimated):.2f}")
        print(f"M-MESH Average Time over {len(mmesh_total_time)}: {np.mean(mmesh_total_time):.2f} seconds - Standard Deviation: {np.std(mmesh_total_time):.2f} seconds")
        print(f"Vanilla Average Visited over {len(vanilla_total_visited)}: {np.mean(vanilla_total_visited):.2f} - Standard Deviation: {np.std(vanilla_total_visited):.2f}")
        print(f"Vanilla Average Expanded over {len(vanilla_total_expanded)}: {np.mean(vanilla_total_expanded):.2f} - Standard Deviation: {np.std(vanilla_total_expanded):.2f}")
        print(f"Vanilla Average Estimated over {len(vanilla_total_estimated)}: {np.mean(vanilla_total_estimated):.2f} - Standard Deviation: {np.std(vanilla_total_estimated):.2f}")
        print(f"Vanilla Average Time over {len(vanilla_total_time)}: {np.mean(vanilla_total_time):.2f} seconds - Standard Deviation: {np.std(vanilla_total_time):.2f} seconds")


if __name__ == "__main__":
    with torch.no_grad():
        absl.app.run(main)
